/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AircraftActions: typeof import('./src/components/AircraftActions.vue')['default']
    Antenna: typeof import('./src/components/icons/Antenna.vue')['default']
    ChangeAltitudeForm: typeof import('./src/components/ChangeAltitudeForm.vue')['default']
    ClearanceDeliveryForm: typeof import('./src/components/ClearanceDeliveryForm.vue')['default']
    CreateAircraftForm: typeof import('./src/components/CreateAircraftForm.vue')['default']
    CreateArrivalAircraftForm: typeof import('./src/components/CreateArrivalAircraftForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    Taxi2BayForm: typeof import('./src/components/Taxi2BayForm.vue')['default']
    TaxiToForm: typeof import('./src/components/TaxiToForm.vue')['default']
    Wifi: typeof import('./src/components/icons/Wifi.vue')['default']
  }
}
